### ISSUE TITLE
Two issues Im seeing

### ISSUE THREAD

**Issue by matprophet** [McNeight/CAN_Library#10]
Neil,

Im using the library with an Arduino Uno and a SparkFun CanBus shield.  Im seeing two different things and I wonder if you would have some feedback:

1.)  CAN.available() always returns 0 for me.  Immediately after setup, and anytime afterwards.  Is this expected?

2.)  When I run my very basic test project to send data to the can bus, see in the logs "write2" after my calls to CAN.write() only 3 times and then it stops, no matter how many more calls I make to CAN.write().  I checked the source and it looks like I've filled the write buffers, but I had assumed that the buffers would clear themselves without a secondary "reader" device  on the line to clear them.  Is that a correct assumption?

Many thanks,
Mat

**Comment by matprophet** [comment]
Ok, small update:
1.)  Should have read the documentation, I see why available() was always returning 0. I was confused, I thought it was for the availability of the write buffers.  Oops.
2.)  I think I may have a hardware issue here.  The buffers are full because I don't have my board plugged into anything.  The spec says the bus needs to be terminated by a 120 Ohm resistor, so Im going to try that and see what happens.

- m

**Comment by coryjfowler** [comment]
> I don't have my board plugged into anything

A healthy CAN bus will require two **active** CAN devices on it.  When one device sends a message, it expects another device on the bus to acknowledge that message otherwise it is interpreted as a failure to send the message.

**Comment by matprophet** [comment]
Breakthrough: I soldered in 60 Ohms across the CAN H and L lines (to simulate 120 Ohm at each end of the bus, as per the spec) and *bingo* Im seeing data leave the Arduino and be received by my RaceCapture unit.
